before:
  hooks:
    - go mod tidy
blobs:
  - provider: gs
    bucket: shopify-terraform-private-registry
    folder: providers/shopify/{{ .ProjectName }}/{{ .Version }}
    extra_files:
    - glob: terraform-registry-manifest.json
      name_template: manifest.json
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    binary: "{{ .ProjectName }}_v{{ .Version }}"
archives:
  - format: zip
    name_template: "{{ .Os }}_{{ .Arch }}"
checksum:
  extra_files:
    - glob: terraform-registry-manifest.json
      name_template: "manifest.json"
  name_template: "SHA256SUMS"
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
